### ISSUE TITLE
Issue: ❓ Support Question

### ISSUE THREAD

**Issue by Theolodewijk** [unreal4u/telegram-api#116]
I tray to get some info bot Telegram don't reply support tickets!

Can you help me with Telegram. so that I am sent in the right direction.

I work for a government organization and we have a weekly exercise, now I would like to simplify this with, for example, a poll or something else where if someone responds to that I get a feedback via the telegram API.

I want to use PHP for this but see many options on the Telegram website https://core.telegram.org/bots/samples#php but now which one is and is not suitable for this and there is a little explanation somewhere how to find it tackles this?

https://telegram.org/blog/polls-2-0-vmq

Greetings Theo

**Comment by unreal4u** [comment]
Hi @Theolodewijk 

This (and other libraries) are wrappers around the actual API, so that you don't have to worry about the installation itself, but rather worry about the actual logic behind each option. We all use very different mechanisms to achieve the same goal, so feel free to choose the one which you feel most comfortable with.

Now speaking of implementing polls in the library itself, this library supports the Bot API up until v4.3, while the polls were actually implemented in v4.6: this means that this library does not support them yet, however, this will be done in the short term.

Greetings and I hope this answer helps you in the way. Feel free to reopen it if you have more questions.
