### ISSUE TITLE
Async Requests

### ISSUE THREAD

**Issue by unreal4u** [unreal4u/telegram-api#13]
Followup of https://github.com/unreal4u/telegram-api/issues/7

Enable async requests via Guzzle (or even better, per PSR definition)

**Comment by unreal4u** [comment]
This is going to be trickier than I thought it would be, mainly because we must expect an answer back. 

I see two options:
1- Promises. (See https://github.com/guzzle/promises and this very informative answer: https://github.com/guzzle/guzzle/issues/1429#issuecomment-197152914 )
2- Build in a check per TelegramMethod whether it should be possible to send out an async request or not.

Maybe combining those two it will be possible to implement this in a way.

**Comment by Yoshi2889** [comment]
This has been partially implemented with #50 but this implementation isn't working, likely due to Guzzle not really having an async implementation although it claims it has.

The alternative could be going with https://github.com/reactphp/http-client and creating a separate `AsyncTgLog` class, perhaps, which would take a LoopInterface to do its work.

**Comment by Yoshi2889** [comment]
I'd say the groundwork for the API is done here, async requests using different handlers can be provided using the new RequestHandlers, and since Guzzle doesn't allow true async requests in its current state there is no point in trying.

One thing we should still change is to implement our own promise for this, so to not rely on the Guzzle promises. Alternatively if reactphp/promise doesn't pull in more dependencies we could use that.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Yoshi2889** [comment]
Promise issue fixed with #52

**Comment by unreal4u** [comment]
merged! Thanks, I'm closing this one now :)
