### ISSUE TITLE
traverseObject is not found at TelegramTypes

### ISSUE THREAD

**Issue by mohammadsavadkuhi** [unreal4u/telegram-api#21]
$arrayOfUpdate = $tgLog ->performApiRequest($getUpdate) ;

   $updates =  $arrayOfUpdate -> traverseObject () ;

**Comment by unreal4u** [comment]
Hi!

This happens because a performApiRequest() will return a TelegramType object, while an array of updates is actually a custom type that extends the TelegramType, but does (additionally) implement the traverseObject() method (as this object is iterable).

Since there is no way of knowing at the stage of an ApiRequest what type of object will be returned, there is no way this can be solved at this stage in an elegant way. Therefor, I'll close this issue as there is no fix for it now.
In the future, if I decide to go with another approach, this issue may get fixed and each method can get it's own (proper) return type(s).

For now, what you can do is instruct your IDE the type of data you're expecting, by typing the following comment: 

```
    $updates = $tgLog->performApiRequest($getUpdates);
    /* @var \unreal4u\TelegramAPI\Telegram\Types\Custom\UpdatesArray $updates */
    foreach ($updates->traverseObject() as $update) {
        // Whatever you want to do
    }
```

This is also useful for any method that can return an array of objects: getChatMembers, GetGameScore, Markup, entities, etc.
