### ISSUE TITLE
Got Error 

### ISSUE THREAD

**Issue by shakibonline** [unreal4u/telegram-api#31]
Hi.
I'm trying use this library. bot i get this error 

![capture](https://user-images.githubusercontent.com/17107543/27259701-61cfdc04-542e-11e7-8c53-389525dee0a8.PNG)

This is my code. simple `getme`.

```php
$tgLog = new TgLog($botToken);

        $getMe = new GetMe();

        try {
            $response = $tgLog->performApiRequest($getMe);
            echo '<pre>';
            var_dump($response);
            echo '</pre>';
        } catch (ClientException $e) {
            // Do whatever you want, function below contains exact JSON output from Telegram
            echo 'Exception catched, error is: <pre>';
            print_r(json_decode((string)$e->getResponse()->getBody()));
            echo '</pre>';
        }
```

ps: I'm using `ngrok` for testing.

**Comment by unreal4u** [comment]
Hi! This definitively has something to do with ngrok, as curl says there is a self-signed certificate in the way (which prevents it from talking directly to the Telegram servers)

I could maybe add a development mode and disable certificate checks, however this may open a security risk as there is no other way of making sure you're actually talking to the telegram servers or some intermediate, such as the case with ngrok with this setting enabled. 

The first thing I can do however is checking if ngrok has some kind of library with which I can work with. I'll keep you posted. 

Greetings.

**Comment by unreal4u** [comment]
Damn, can't test this because I need a paid plan: 

```
unreal4u-MBP:Downloads unreal4u$ ./ngrok tls -hostname=mbp.unreal4u.com 443
Tunnel session failed: TLS tunnels are only available for Pro and Business paid plans.
Sign up at: https://ngrok.com/signup

If you have already signed up, make sure your authtoken is installed.
Your authtoken is available on your dashboard: https://dashboard.ngrok.com

ERR_NGROK_303
```

But from what I could read about it on this link: 

https://ngrok.com/docs#tls-cert-warnings

You'll have to purchase a certificate (hint: you could also do it for free with letsencrypt) in order to be able to generate no warnings on connection.

My best guess is that without ngrok you won't have this issue, could you try to disable ngrok and make the request? It should work as you are requesting a document from the Telegram servers, they are not trying to contact you (except for trying to send updates to you, but you can survive in a development environment with the [getUpdates method](https://github.com/unreal4u/telegram-api/blob/master/examples/get-updates.php)).

Greetings.

**Comment by unreal4u** [comment]
Hi! Did you have any luck without ngrok?

**Comment by unreal4u** [comment]
Btw, have you tried this? https://stackoverflow.com/a/32812595

**Comment by shakibonline** [comment]
Sorry, i am busy right now, but i will do some test and report to you.

**Comment by unreal4u** [comment]
Ok, I'm closing this for now then. Feel free to reopen or create a new issue should the need arise :)

Thanks!
