### ISSUE TITLE
Strange issue: Class 'unreal4u\TelegramAPI\Telegram\Types\SuccessFulPayment' not found

### ISSUE THREAD

**Issue by ircop** [unreal4u/telegram-api#34]
Hello!

I have strange issue with payments API: after successfull payment, when Telegram sends to bot message of the type successful_payment , i have following error:

```
Unhandled error occured on face1!

Class 'unreal4u\TelegramAPI\Telegram\Types\SuccessFulPayment' not found
/var/www/tg-dev/vendor/unreal4u/telegram-api/src/Telegram/Types/Message.php:313
```

But i cannot fastly find any problems, all files, classes & namespaces seems to be ok...

**Comment by ircop** [comment]
Ah, i got it.

You have in Message.php:
```
return new SuccessFulPayment
```

but its Successful, not SuccessFull

**Comment by unreal4u** [comment]
oh that's a big typo lol ... 

I'll fix it immediatly :) Thanks for reporting!

**Comment by unreal4u** [comment]
PS: Just noticed that the class (and file) have the correct name: https://github.com/unreal4u/telegram-api/blob/master/src/Telegram/Types/SuccessfulPayment.php so that's not the problem

Can you check whether the class is correctly found in `vendor/composer/autoload_classmap.php`? Also a `git status` output on `vendor/unreal4u/telegram-api` would be useful for me to check :)

**Comment by unreal4u** [comment]
oooh I see it, it's the F! Sorry, will fix it right away

**Comment by unreal4u** [comment]
There you go! Version https://github.com/unreal4u/telegram-api/releases/tag/v2.4.3 is ready and fixes this issue, thanks a lot for all the created issues so far!

**Comment by ircop** [comment]
Thank you!
