### ISSUE TITLE
Fatal error removing a webhook

### ISSUE THREAD

**Issue by Ardaking** [unreal4u/telegram-api#36]
Using the wiki for setting up a webhook (https://github.com/unreal4u/telegram-api/wiki/Getting-updates-via-Webhook) then when using an empty URL to remove the webhook defined, a fatal error occours because url is mandatory.

I suggest to provide a separated class to solve this.

Thanks
Denis

**Comment by Ardaking** [comment]
Anyways DeleteWebhook provide what is expected

**Comment by unreal4u** [comment]
I didn't make a separate class, because I would like to stay as close as possible to the API implementation by Telegram itself, so instead of a separate class, I simply removed the default empty string value: null is still empty, a string will still be enforced by PHP and it will fail (as it should) if no value is set. As for the other cases: setting it was already mandatory, and unsetting your webhook is now possible by just following the rules of the API: as simple as passing an empty string.

I also wrote some unit tests to cover this scenario so it won't accidentally happen again :)

Thanks for catching this one! Greetings :)
