### ISSUE TITLE
reading promise

### ISSUE THREAD

**Issue by raaaas** [unreal4u/telegram-api#62]
hey, 

thanks for great code, but i could not read value by 

            $output = $getChatMembersCountPromise->then(
                function (ResultInt $getChatMembersCountResponse) {
                   return $getChatMembersCountResponse;
                    
                },
                function (ClientException $e) {
                    return $e->getError();
                }
            );

return $output

but when i add echo its work fine but wont assaign it to any variable 

any help ?

**Comment by unreal4u** [comment]
Hi! Sorry for the late response, I've been quite busy lately :)

A promise is -as the name implies- a promise of a to-be-executed-function: at the time you are evaluating $output, no code has been executed yet.

In order to do what you want to do, I suggest taking a look at the following example:
https://github.com/unreal4u/telegram-api/blob/master/examples/01.blocking-get-me.php

That example creates a blocking request which will wait until returning a value to go further the line. In any other case, you'll have to perform all your actions in the actual first closure.

Greetings.

**Comment by raaaas** [comment]
Thank you work like charm

**Comment by unreal4u** [comment]
You're welcome, closing this one :)
