### ISSUE TITLE
Roadmap for 2.* and 3.*

### ISSUE THREAD

**Issue by kettari** [unreal4u/telegram-api#63]
Hi!

Could you please point me to your lifecycle roadmap of of 2.* and 3.* versions? I'm happy with v2 and do not plan to upgrade in the nearest future. About 5 projects use second version... So it would be nice to know what to expect in next 365 days :)

**Comment by unreal4u** [comment]
Hi, as of now, v2 and v3 are pretty much the same, except for the actual http client. As such, maintaining both shouldn't be that much of a problem. I actually did that while launching v2.7.0, and it was pretty easy.

That being said, I think I'll actively maintain v2 until at least April 2018, and depending on the number of downloads for v2 by then, I'll re-evaluate and maybe extend it for another 3 or 6 months.

Another option is maybe include some sort of wrapper to ease the transition. You can always fall back to a blocking request in order to avoid much of the hazzle: https://github.com/unreal4u/telegram-api/blob/master/examples/01.blocking-get-me.php

I'll update the readme however to include the roadmap. Thanks!
