### ISSUE TITLE
Android telegram client scroll down after callback

### ISSUE THREAD

**Issue by sautchenkov** [unreal4u/telegram-api#70]
Hi! I have some problems with android telegram client. If I send a message with a link and callback button for this message, after press callback button client app force scroll down to the end of bot conversation.

This reproduce only in android client and only if a message has a link and callback button.

Maybe anyone one knows what I can do with this?

**Comment by unreal4u** [comment]
Hi! Sorry it took so long to answer, had some small vacations :)

This isn't an issue that you can solve with the bot api, so my suggestion would be to talk to either BotSupport or contact Telegram's support (you can contact them through the app) to either inform them of this bug or ask whether it's normal behaviour. 

Because it is not something this api can fix, I'll close it for now. Feel free to reopen it at any time. 

Greetings.
